name: Deploy to VPS

on:
  push:
    branches:
      - deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.17'

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'

      - name: Build Backend
        working-directory: ./backend
        env:
          GOOS: linux
          GOARCH: amd64
        run: go build -o backend

      - name: Prepare Directory Structure
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT || '22' }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /ppmg/kamen/2024-project/frontend/.next
            mkdir -p /ppmg/kamen/2024-project/backend
            chmod -R 755 /ppmg/kamen/2024-project
            echo "Directory structure created and permissions set"
            ls -la /ppmg/kamen/2024-project/frontend

      - name: Debug Remote Environment
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT || '22' }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            pwd
            whoami
            ls -la /ppmg/kamen/2024-project
            df -h /ppmg/kamen/2024-project

      - name: Copy Frontend Files
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT || '22' }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "frontend/.next/*"
          target: "/ppmg/kamen/2024-project/frontend/.next"
          strip_components: 2
          overwrite: true

      - name: Copy Backend Files
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT || '22' }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "backend/backend"
          target: "/ppmg/kamen/2024-project/backend"
          strip_components: 1
          overwrite: true

      - name: Verify Deployment and Restart Services
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT || '22' }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Verifying deployment..."
            ls -la /ppmg/kamen/2024-project/frontend/.next
            ls -la /ppmg/kamen/2024-project/backend
            
            echo "Restarting services..."
            cd /ppmg/kamen/2024-project/frontend
            pm2 restart 0 || echo "PM2 restart failed"
            
            sudo systemctl daemon-reload
            sudo systemctl restart contestify_backend
            sudo systemctl enable contestify_backend
            
            echo "Deployment complete"