name: Update Deployment

on:
  push:
    branches:
      - deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.17'

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'

      - name: Build Backend
        working-directory: ./backend
        env:
          GOOS: linux
          GOARCH: amd64
        run: go build -o backend

      - name: Stop Services
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT || '22' }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Stopping services..."
            pm2 stop 0 || echo "PM2 stop failed"
            sudo systemctl stop contestify_backend || echo "Backend stop failed"
            # Give processes time to fully stop
            sleep 5

      - name: Update Frontend Files
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT || '22' }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "frontend/.next/"
          target: "/home/kamen/2024-project/frontend/"
          overwrite: true

      - name: Update Backend Executable
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT || '22' }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Removing old backend executable..."
            rm -f /home/kamen/2024-project/backend/backend

      - name: Copy New Backend Executable
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT || '22' }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "backend/backend"
          target: "/home/kamen/2024-project/backend/"
          overwrite: true

      - name: Start Services
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT || '22' }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Setting permissions..."
            chmod 755 /home/kamen/2024-project/backend/backend
            
            echo "Starting services..."
            cd /home/kamen/2024-project/frontend
            pm2 start 0
            
            echo "Starting backend service..."
            sudo systemctl daemon-reload
            sudo systemctl start contestify_backend
            sudo systemctl enable contestify_backend
            
            echo "Verifying services..."
            pm2 list
            sudo systemctl status contestify_backend --no-pager
            
            echo "Deployment complete"